# Generated by Django 2.1.5 on 2019-03-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxnDate', models.DateField()),
                ('ValueDate', models.DateField()),
                ('Description', models.TextField(blank=True)),
                ('Debit', models.FloatField(blank=True, default=None, null=True)),
                ('Credit', models.FloatField(blank=True, default=None, null=True)),
                ('Balance', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
