# Generated by Django 2.1.5 on 2019-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Description',
            new_name='statement',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Credit',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Debit',
        ),
        migrations.RemoveField(
            model_name='details',
            name='TxnDate',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ValueDate',
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
