# Generated by Django 2.1.5 on 2019-03-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190330_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='balance',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='credit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='debit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='txndate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='valdate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
