# Generated by Django 2.1.7 on 2019-04-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190401_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing',
        ),
        migrations.AlterField(
            model_name='save',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
